version: '3.0'

networks:
  laravel:

services:
  lossgain_nginx:
    image: nginx:latest
    container_name: lossgain_nginx
    ports:
      - "3000:30"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lossgain_php
      - lossgain_mysql
    networks:
      - laravel

  lossgain_mysql:
    build:
      context: ./docker/mysql
    container_name: lossgain_mysql
    command: --max_allowed_packet=32505856
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lossgain
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: lossgain
      MYSQL_PASSWORD: lossgain
      SERVICE_TAGS: dev
      SERVICE_NAME: lossgain_mysql
    networks:
      - laravel

  lossgain_php:
    build:
      context: ./docker/php
    working_dir: /var/www/html
    container_name: lossgain_php
    volumes:
      - .docker/php/php-ini-overrides.ini:/etc/php/conf.d/php-ini-overrides.ini
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
    environment: 
      - COMPOSER_MEMORY_LIMIT=-1

  lossgain_yarn:
    image: node:14.9
    container_name: lossgain_yarn
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['yarn']

  lossgain_artisan:
    build:
      context: ./docker/php
    container_name: lossgain_artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - lossgain_mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
